/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "9e8d8c4830c1ab7c491b98f134cbe19761eaf033"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
