/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "6f828b7c947e4ef81401924cde65429d246f0225"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
